version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

# conda:
#   environment: docs/environment.yml

# build:
#   image: latest
#   apt_packages:
#     - clang-13
#     - cmake
#     - libclang-13-dev
#     - llvm-13-dev
#     - llvm-13-tools

# version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - clang-13
    - cmake
    - libclang-13-dev
    - llvm-13-dev
    - llvm-13-tools
  # jobs:
  #   pre_build:
  #   # Note that this HTML won't be automatically uploaded,
  #   # unless your documentation build includes it somehow.
  #   - mkdir build
  #   - cd build
  #   - cmake ../ -DINTEROP_ENABLE_DOXYGEN=ON\ -DINTEROP_INCLUDE_DOCS=ON'
  #   - doxygen /build/docs/doxygen.cfg