version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

# conda:
#   environment: docs/environment.yml

# build:
#   image: latest
#   apt_packages:
#     - clang-13
#     - cmake
#     - libclang-13-dev
#     - llvm-13-dev
#     - llvm-13-tools

# version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
    # Note that this HTML won't be automatically uploaded,
    # unless your documentation build includes it somehow.
      - doxygen