version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

# conda:
#   environment: docs/environment.yml

# build:
#   image: latest
#   apt_packages:
#     - clang-13
#     - cmake
#     - libclang-13-dev
#     - llvm-13-dev
#     - llvm-13-tools

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - cmake
  commands:
    - pip install llvm-installer